### ISSUE TITLE
Terminal support?

### ISSUE THREAD

**Issue by ether42** [weirdNox/emacs-gdb#2]
Hi there,

From the screenshot it seemed promising but it looks like it makes use of GUI-only features.

I tried to comment out `(define-fringe-bitmap 'gdb--fringe-breakpoint "\x3c\x7e\xff\xff\xff\xff\x7e\x3c")` because `define-fringe-bitmap` isn't available and I could at least start an executable.
However, there are some rendering artifacts (in the asciinema below I have to either move the cursor to redraw lines or do a `C-l` to redraw the whole screen toward the end).
There is also no GDB prompt so I'm thinking I'm probably doing something stupid or that there is no terminal support yet (as the readme says that the interface may become out of sync when sending commands directly).
I must admit I didn't investigate much more than that :)

Here is the asciinema: https://asciinema.org/a/WPp7DiWvNwmkwL6hCUgV0xN70

By the way, I used the following use-package/[straight](https://github.com/raxod502/straight.el) declaration in case you want to add it to the readme too:
```elisp
(use-package gdb-mi
  :straight (:host github :repo "weirdNox/emacs-gdb" :files ("*.el" "*.c" "*.h" "Makefile"))
  :init
  (fmakunbound 'gdb)
  (fmakunbound 'gdb-enable-debug))
```

Tested with Emacs 26.1.

Feel free to close the issue if you don't intend to support this use case.

Regards.

**Comment by weirdNox** [comment]
Terminal support should be a available, so thanks for the report! I don't use it much, but it shouldn't be hard to do! :)

**Comment by weirdNox** [comment]
Could you try the last commit? I believe the problem was that it wasn't focusing the new frame, which is needed. I also fixed the problem you had with `define-fringe-bitmap` (I think!). It worked for me in Konsole, but please test it yourself and give feedback :)

**Comment by ether42** [comment]
That's much better, thanks!

I'll close the issue but I have a couple more of questions & remarks after playing with it for a couple of minutes so I'll derail the thread :)

- it seems the interface is heavily refreshed (for example `f10` or `next` will refresh the whole terminal, making it flash/slow)
- I'm unsure about the thread handling: I selected one in the thread buffer and tried to `up` into the call stack but the source buffer didn't refresh to follow even though GDB told me the lines, which is the default behavior in something like [cgdb](https://cgdb.github.io/) (which I would gladly trade with something Emacs-based but I recall having some problems with GUD, and this one is always tricky because it's always difficult to chose between opening a new buffer or reusing the existing one to display another file)
- I presume I could change the default keybindings (not a fan of functions keys) but I would much prefer having a real GDB prompt than coming up with many shortcuts, the comint buffer seems to be the way to go but it lacks some features I'm accustomed to and is a bit cumbersome to use:
  - last command repetition with enter
  - input handling similar to other front-ends, like command or variable completion and other goodies
  - avoid some noise by not showing the source line on stepping through (unneeded with the source buffer)
  - could have a different handling of the history than `C-<up>` or `C-<down>`

That's it for my first try. Still seems nice but having a real prompt to interact with GDB would make me consider your package.
Don't feel obligated to fix what I just said, that's just some remarks I though I would share (that's what I'm searching for a debugger front-end at least and would love to be able to reuse Emacs).

Thanks.

**Comment by weirdNox** [comment]
Thanks for the feedback :) I don't have much time right now to implement features, but I'll keep it in mind for the future! 

- Yes, I also noticed that, it seems that the terminal display is slower than the graphical one, which is a bummer. If there is new information available, the buffers are completely redrawn because it is hard to maintain coherency of the data with the rendered view and update it only in some parts. Nevertheless, if the source buffer also flashes, I'll have to check it, it uses `(recenter)` to focus the correct line.
- Ok, that's one of the things I warn in the README, as I made this based on the commands provided, I'm ignoring the notification GDB provides when you execute that command. It shouldn't be hard to use this notification to update the stack list.
- Yes, you can rebind everything. 
  - Command repetition should be easy
  - I don't know how I could get the completion from GDB, do you have any idea?
  - I could filter out all console output from appearing, we would also lose `[Thread ... created]`, and such, but that could be recreated
  - There is a command history provided by the comint mode using `M-<up>` and `M-<down>`, is that what you want?

Anyway, thanks for trying this out and for the feedback provided! I hope this eventually becomes something you like using :)

**Comment by weirdNox** [comment]
Ok, command repetition is done :D

**Comment by weirdNox** [comment]
Ok, we now have command repetition, much better GDB prompt, and the `up` and `down` commands are working!

**Comment by weirdNox** [comment]
Ok, completion at point is working! :) I didn't know the original had it, but eventually I found about that `complete` command and added support in the module.
I think the glitch you are referring to may also be fixed.

I put the comint and the source buffer in the same place because I don't use the comint buffer too much, so it was like a placeholder for the window while there is no source buffer to present. But, like you said, you may create another function based on `gdb--setup-windows` and change the variable `gdb-window-setup-function` to its symbol.

I also removed the first compilation. The idea was to compile when the package was installed, but it is very unpredictable, so goodbye ahah.

Thanks for the suggestions, implementing this was great :D

**Comment by ether42** [comment]
For `gdb--setup-windows` it seems the user can't `(setf (gdb--session-source-window session) top-left)` without getting `Symbol’s function definition is void: \(setf\ gdb--session-source-window\)` (that's probably a mistake from my side but this is by simply copy/pasting your implementation of `gdb--setup-windows` into a lambda).

Here is what I'm trying to do (requires #4):
```elisp
(defun ether--gdb-executable (switch)
  "Debug an executable with GDB, taking care of settings arguments."
  (ignore switch)
  (let ((executable (pop command-line-args-left))
        (quoted-arguments (combine-and-quote-strings
                           (mapc (lambda (_) (pop command-line-args-left)) command-line-args-left))))
    (gdb-executable executable)
    (gdb--command (concat "set args " quoted-arguments)))
  t) ; done

(use-package gdb-mi
  :straight (:host github :repo "weirdNox/emacs-gdb" :files ("*.el" "*.c" "*.h" "Makefile"))
  :config
  (setq gdb-ignore-gdbinit nil
        gdb-window-setup-function (lambda (session)
                                    (with-selected-frame (gdb--session-frame session)
                                      (delete-other-windows)
                                      (let* ((height (window-size nil))
                                             (top-left (selected-window))
                                             (bottom-left (split-window top-left (* 2 (/ height 3))))
                                             (bottom-right-top (split-window bottom-left nil t))
                                             (bottom-right-bottom (split-window bottom-right-top nil nil))
                                             (top-right (split-window top-left nil t)))
                                        (gdb--set-window-buffer top-right (gdb--comint-get-buffer session))
                                        (gdb--set-window-buffer bottom-left (gdb--variables-get-buffer session))
                                        (gdb--set-window-buffer bottom-right-top (gdb--threads-get-buffer session))
                                        (gdb--set-window-buffer bottom-right-bottom (gdb--breakpoints-get-buffer session))
                                        ;; broken for now?
                                        ;; (setf (gdb--session-source-window session) top-left)
                                        (gdb--display-source-buffer))) ; switch to frame
                                    (switch-to-buffer-other-window (gdb--comint-get-buffer session))))
  :init
  (add-to-list 'command-switch-alist '("--gdb" . ether--gdb-executable))
  (fmakunbound 'gdb)
  (fmakunbound 'gdb-enable-debug))
```

So I can directly `emacs --gdb a.out 1 '2 3' '4 > 5'` (inspired by `gdb --args`) :)

What do you do to get the program's output? I recall other debuggers just print it out (I wonder if they pipe stdout/stderr of the process as to not mess up their own output).

**Comment by ether42** [comment]
Unfortunately, it seems I don't get the line and breakpoint markers in the source anymore.

On a super low priority (because there is the variables buffer which offer a better alternative), I think the `display` command used to show variables at each command but now it only works for the first (seems related to df81088). So some commands may encounter similar issues.

**Comment by weirdNox** [comment]
> Well... I think I just understood: I'm switching manually to the buffer

Does it work if you try with the F12 key?

About the setf problem, I found this: https://github.com/flycheck/flycheck/issues/1398
It confirms my fear, it tries to expand the setf when loading the configuration file, which means `gdb-mi` is not loaded yet and so `setf` doesn't know what the place is.

I found a workaround which works:
```elisp
(setq gdb-ignore-gdbinit nil
        gdb-window-setup-function
	(eval
	 '(lambda (session)
	    (with-selected-frame (gdb--session-frame session)
	      (delete-other-windows)
	      (let* ((first (selected-window))
		     (second (split-window first)))
		(setf (gdb--session-source-window session) first)
		(gdb--set-window-buffer second (gdb--comint-get-buffer session))
		(gdb--display-source-buffer))))))
```

This way, Emacs only evaluates the defun after loading. Nevertheless, I'm going to change it in order to remove the dependency on `setf`.

**Comment by weirdNox** [comment]
Ok, done, please see the new definition in order to write your own :)

**Comment by ether42** [comment]
> Does it work if you try with the F12 key?

Yes it does. But kinda defeats the purpose of `gdb-window-setup-function` :)

> Ok, done, please see the new definition in order to write your own :)

And it works, thanks (and the user interface is simpler too)!

**Comment by weirdNox** [comment]
Ok great! Happy that we ironed this out :)
