### ISSUE TITLE
Emacs26 dependency

### ISSUE THREAD

**Issue by marlinstrub** [weirdNox/emacs-gdb#8]
I'm using Emacs 25.3.2 on Ubuntu 18.04, trying to install emacs-gdb gives `error: Package ‘emacs-26.1’ is unavailable`. Is there any way I can install emacs-gdb without upgrading to Emacs26? Thanks!

**Comment by weirdNox** [comment]
Hi! I put that requirement because that's what I used for developing this. Could you try downloading this repo manually and then executing `(eval-buffer)` on `gdb-mi.el`? Just make sure you have `hydra` installed and, if that version is compatible, it should work. If it works, I'll lower the restriction to that version.

**Comment by marlinstrub** [comment]
Hi. `(eval-buffer)` on `gdb-mi.el` claimed it installed successfully. Trying to run it on a test program, however, gives `error in process filter: cond: Unexpected table-or-argument type`. I suppose I either have to upgrade or stick with the default gdb-mi... thanks for the reply!

**Comment by weirdNox** [comment]
Ok, it looks the user defined types (records) were only added in 26.1.

As those are used for `cl-defstruct`, and this depends on them for identification, my initial requirement was right after all ahah

Thanks for bringing this up anyway :)

**Comment by marlinstrub** [comment]
Thanks for looking into it!
